### ISSUE TITLE
Rahmenplan mit wichtigen Meilensteinen und Sprints

### ISSUE THREAD

**Issue by alexander-suter** [alexander-suter/appe-pmp#1]

**Comment by wuethrich44** [comment]
Meilensteine mit Ergebnissen hinzufügen

**Comment by wuethrich44** [comment]
![image](https://cloud.githubusercontent.com/assets/6050639/6504914/aedbdd34-c33c-11e4-963d-7cc350fd3326.png)

**Comment by alexander-suter** [comment]
Könntest Du nochmals reinschauen?
Ich schneide, das PDF am Schluss zu.


Falls es ok ist, dann müssen wir in ScrumDo noch die Iterationen erstellen.

**Comment by wuethrich44** [comment]
Sed alles gued us hanen scho zugschnitte
