### ISSUE TITLE
Risiken

### ISSUE THREAD

**Issue by alexander-suter** [alexander-suter/appe-pmp#4]

**Comment by wuethrich44** [comment]
Wichtiges Risiko: Technologie die man nicht kennt

**Comment by alexander-suter** [comment]
Hier noch ein Beispiel von uns aus VSK:

![image](https://cloud.githubusercontent.com/assets/7498380/6545813/087572f6-c59a-11e4-9e85-0f457b99961e.png)

**Comment by wuethrich44** [comment]
@alexander-suter Review please

**Comment by alexander-suter** [comment]
enterprise lab gelegentlich nicht verfügbar :+1:
