### ISSUE TITLE
Offizielle PMP Kapitel erstellen und beschreiben

### ISSUE THREAD

**Issue by alexander-suter** [alexander-suter/appe-pmp#6]
Es gibt noch eine Kapitel welche definiert werden müss, nach offiziellem PMP.

**Comment by alexander-suter** [comment]
Sali.

Ich ha mals gröbste im PMP gmacht.

Chasch mal alles aluege? Ich ha mich jetzt eifahcmal zum Projektleiter erkore, falls es eine vo euch mache wott - nur zue - aber ich ha denkt es wott eh niemmer friwillig.

Wär cool, wenn mer de PMP die Wuche chönded scho fertig mache bis ufs Kapitel Testplan.

**Comment by wuethrich44** [comment]
Ha no es paar sache korrigiert suscht perfekt! Ich mach hüt no Risikomanagement und e Tabelle fürs Konfigurationsmanagement

**Comment by alexander-suter** [comment]
super danke
